### ISSUE TITLE
Example doesn't work?

### ISSUE THREAD

**Issue by spaceotter** [m2ym/optima#117]
Maybe I'm missing something...
`CL-USER> (optima:match 1 ((guard x (eql x 1)) t))
; Evaluation aborted on #<SIMPLE-ERROR "Non-linear pattern: ~S" {1007CCFA43}>.`

**Comment by m2ym** [comment]
Maybe `guard` is missing and should be `optima:guard` here.

**Comment by spaceotter** [comment]
Sorry, I'm still new at lisp... I need to use-package.
