### ISSUE TITLE
Quasiquotation error on SBCL(1.3.0.56-976267b)

### ISSUE THREAD

**Issue by byulparan** [m2ym/optima#118]
```
(match '(1 2 3 4) 
    (`(1 ,x ,@y) (list x y)))
```

in CCL => (2 (3 4))
but SBCL(1.3.0.56-976267b) => error.  1 is not a string designator.

**Comment by m2ym** [comment]
Do you use fare-quasiquote?

**Comment by byulparan** [comment]
Ah! .. I don't know fare-quasiquote before..., but now It's OK. 
sorry for noise. Thank you!
