### ISSUE TITLE
“Recommended” status on CLiki

### ISSUE THREAD

**Issue by akater** [m2ym/optima#123]
Hello. I'm doing some revisions and cleanup on CLiki. At this moment, optima shows up in Current Recommended Libraries on CLiki while trivia does not. I believe it should be replaced with trivia. Do you agree? Both pages mention each other of course.

I added “deprecated” status to optima's page. If you find this label incorrect, please tell. Thank you.

**Comment by guicho271828** [comment]
I don't know who edits Cliki actively recently (I don't think there are many), and I don't think it has any authority status. So you can edit it at any time.

**Comment by akater** [comment]
Not many, true. Thank you!
